import { Lightbulb, RefreshCw, Sparkles } from "lucide-react";
import { useFetch } from "../../lib/useFetch";
import { Button, Card, CardHeader, Skeleton } from "../../components/ui";

export const AIInsightsCard = () => {
  const { data, error, loading, reload } = useFetch("/ai/dashboard-insights");

  return (
    <Card>
      <CardHeader
        title={
          <span className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-brand-600" /> AI insights
          </span>
        }
        description="Generated by Gemini from recent performance reviews"
        action={<Button variant="ghost" size="icon" onClick={reload} aria-label="Refresh insights" disabled={loading}><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /></Button>}
      />
      <div className="p-5">
        {loading ? (
          <div className="space-y-3">
            {[0, 1, 2, 3].map((i) => <Skeleton key={i} className="h-4 w-full" />)}
          </div>
        ) : error ? (
          <p className="text-sm text-slate-500">{error}</p>
        ) : (
          <ul className="space-y-3">
            {(data?.insights || []).map((text, i) => (
              <li key={i} className="flex gap-3 text-sm text-slate-700">
                <Lightbulb className="mt-0.5 h-4 w-4 shrink-0 text-amber-500" />
                <span>{text}</span>
              </li>
            ))}
          </ul>
        )}
      </div>
    </Card>
  );
};
